generate_features: True
preprocess: False
train_model: False
random_seed: False

atom_types:
- 'species1'
- 'species2'
- 'species3'
params:
    species1: 'your/dir/to/parameter/species1'
    species2: 'your/dir/to/parameter/species2'
    species3: 'your/dir/to/parameter/species3'

#Input for generate fearues
descriptor: 
    type: 'symmetry_function'
    struct_list: './structure_list'
    save_list: './total_list'
    refdata_format: 'vasp-out'
    compress_outcar: False
    save_directory: './data'
    read_force: True
    read_stress: True 
    dx_save_sparse: False
    add_atom_idx: True 
    absolute_path: False
#Input for preprocess
preprocessing: 
    data_list: './total_list'
    train_list: './train_list'
    valid_list: './valid_list' 
    shuffle: True
    valid_rate: 0.0
    #PCA 
    calc_pca: True
    pca_whiten: True
    pca_min_whiten_level: 1.0e-8
    #Scaling
    calc_scale: True
    scale_type: 'minmax'
    scale_scale: 1.0
    scale_rho: 1
    #GDF
    calc_gdf: False
    atomic_weights: 
       type: 'gdf'
       params: 
            sigma:
                species1: 0.02
                species2: 0.06
    weight_modifier: 
       type: 'modified_sigmoid'
       params: 
        species1:
          b: 100
#Input for traning
neural_network:
    train_list: './train_list'
    valid_list: './valid_list' 
    test_list: './test_list'
    ref_list: './ref_list'
   
    train: True
    test: False
    add_NNP_ref: False
    train_atomic_E: False

    shuffle_dataloader: True
    workers: 0 

    # Network related
    nodes: '30-30'
    regularization: 1e-6 #L2 regularization
    use_force: True
    use_stress: True

    double_precision: True
    weight_initializer:
        type: 'xavier normal'
#       params:
#           gain: 
#           std: 
#           mean: 
#           var: 
    acti_func: 'sigmoid'
    dropout: False

    # Optimization related
    batch_size: 10
    full_batch: False
    total_epoch: 5
    learning_rate: 0.0001
    lr_decay: 0.1
    stress_coeff: 0.000001
    force_coeff: 0.1 
    energy_coeff: 1.
    loss_scale: 1.
    optimizer:
        method: 'Adam'


    # Loss function related
    E_loss_type: 0
    F_loss_type: 1

    # Logging & saving related (Epoch)
    show_interval: 1
    checkpoint_interval: False
    energy_criteria: False
    force_criteria: False
    stress_criteria: False
#    break_max: 10
    print_structure_rmse: True

    pca: True
    scale: True
    gdf: False

    #RESUME parameters
    continue: False #Checkpoint_file or 'weights'
    clear_prev_status: False
    clear_prev_optimizer: False
    start_epoch: 0
    #Parallelism
    inter_op_parallelism_threads: 0
    intra_op_parallelism_threads: 0
    load_data_to_gpu: False
    cuda_number: False

