generate_features: True
preprocess: True
train_model: True
random_seed: 100

params:
    Si: ./params
    O: ./params

descriptor:
    type: symmetry_function
    compress_outcar: True

preprocessing:
    shuffle:            False
    valid_rate:         0.5
    calc_scale:         True
    scale_type:         minmax
    calc_pca:           True

neural_network:
    train:              True
    shuffle_dataloader: False
    weight_initializer:
        type:           'xavier normal'
    batch_size:         2
    total_epoch:        5
    learning_rate:      0.01
    decay_rate:         0.9
    show_interval:      1
    save_interval:      1
    use_scale:          True
    use_pca:            True
