generate_features: False
preprocess: False
train_model: True
random_seed: 123

params:
    Si: params_Si
    O:  params_O

neural_network:
    nodes: 30-30
    batch_size: 8
    optimizer: 
        method: Adam
    total_epoch: 1000
    learning_rate: 0.001
    scale: True
    pca: True
