generate_features: false
preprocess: false
train_model: true
random_seed: 123

params:
    Si: params_Si
    O:  params_O

neural_network:
    train: false
    test: false
    add_NNP_ref: false
    train_atomic_E: true
    continue: false

    optimizer:
        method: Adam
    nodes: 30-30
    batch_size: 10
    total_epoch: 1000
    learning_rate: 0.001
    scale: true
    pca: true
