generate_features: false
preprocess: false
train_model: true
params:
  Si: params_Si
  O: params_O

neural_network:
  method: Adam
  nodes: 30-30
  batch_size: 10
  epoch: 10
  learning_rate: 0.001
  use_force: true
  pca: true
  scale: true
  gdf: true
  weight_modifier:
    type: modified sigmoid
    params:
      Si:
        b: 1.
        c: 35.
      O:
        b: 1.
        c: 74.
