generate_features: false
preprocess: false
train_model: true
random_seed: 123

params:
    Si: params_Si
    O: params_O

neural_network:
    optimizer:
        method: Adam
    nodes: 30-30
    batch_size: 10
    total_epoch: 1000
    learning_rate: 0.001
    scale: true
    pca: true

    atomic_weights: true
    weight_modifier:
        type: modified sigmoid
        params:
            Si:
                b: 1.
                c: 35.
            O:
                b: 1.
                c: 74.
