generate_features: False
preprocess: False
train_model: True
random_seed: 123

params:
    Si: params_Si
    O:  params_O

neural_network:
    train: False
    test: False
    add_NNP_ref: False
    train_atomic_E: True
    nodes: 30-30
    weight_initializer:
        params:
            gain: 2.0  
    optimizer:
        method: Adam
    total_epoch: 100
    learning_rate: 0.001
    scale: True
    pca: True
